#!/bin/bash
rm -f *.tab dbfile.bin

./db "CREATE TABLE t1 (a int, b int, c char(10))"
./db "CREATE TABLE t2 (a int, d char(10))"
./db "INSERT INTO t1 VALUES (1, 10, 'one')"
./db "INSERT INTO t1 VALUES (2, 20, 'two')"
./db "INSERT INTO t1 VALUES (3, 30, 'three')"
./db "INSERT INTO t1 VALUES (4, 40, 'four')"
./db "INSERT INTO t1 VALUES (5, 50, 'five')"
./db "INSERT INTO t2 VALUES (1, 'match1')"
./db "INSERT INTO t2 VALUES (3, 'match3')"
./db "INSERT INTO t2 VALUES (5, 'match5')"
./db "SELECT * FROM t1"
./db "UPDATE t1 SET b = 99 WHERE a = 1"
./db "SELECT * FROM t1"
./db "DELETE FROM t1 WHERE a = 4"
./db "SELECT * FROM t1"
./db "SELECT a, c FROM t1"
./db "SELECT SUM(b) FROM t1"
./db "SELECT AVG(b) FROM t1"
./db "SELECT COUNT(*) FROM t1"
./db "SELECT * FROM t1 ORDER BY b DESC"
./db "SELECT * FROM t1 NATURAL JOIN t2"
./db "SELECT * FROM t1 NATURAL JOIN t2 WHERE b > 15"
./db "DROP TABLE t1"
./db "DROP TABLE t2"
